### ISSUE TITLE
Update WallE firmware wrt latest ESP-IDF version

### ISSUE THREAD

**Issue by gautam-dev-maker** [SRA-VJTI/Wall-E#108]
Currently the latest ESP-IDF release version is 4.4.1. All the firmware of Wall-E should be updated to be able to compile with that IDF.

**Comment by gautam-dev-maker** [comment]
@Jamm02 @ChinmayLonkar @Sidshx has anyone been assigned to take up this task?

**Comment by ChinmayLonkar** [comment]
@gautam-dev-maker I'll take this task👍

**Comment by ChinmayLonkar** [comment]
@RISHI27-dot you can proceed with this task👍

**Comment by RISHI27-dot** [comment]
I will proceed with this issue.

**Comment by gautam-dev-maker** [comment]
@RISHI27-dot have you identified which firmware crashes or report bugs when esp-idf version is updated?

**Comment by RISHI27-dot** [comment]
I tested the firmware with the latest stable version ESP-IDF v4.4.2-dirty. None of the firmware issues any compilation errors or deprecated API warnings. The 8_sefl_balancing and 3 MPU produce runtime faults related to the I2C, the ESP-IDF version is not to blame for their occurrence :-). Here, I've noted my observation:

| firmware       | build        | flash/monitor | error/crash info |
| ---------------- | ------------- | ----------------- | -------------------- |
| 1_led_blink  | yes           | yes                | -                 |
| 2_LSA  | yes  | yes | - |
| 3_MPU | yes  | no | I2C error |
| 4_switch_controlled_motor_normal | yes  | yes | - |
| 5_switch_controlled_motor_parallel  |yes | yes | - |
| 6_PWM  | yes  | yes | - |
| 7_line_following | yes | yes | - |
| 8_self_balancing  | yes  | no | I2C error |

**Comment by gautam-dev-maker** [comment]
If you are reporting an error, better post the whole `LOG`, else how are we supposed to grasp what error is there.

**Comment by Jamm02** [comment]
@RISHI27-dot Have you tested 4.4 on mainline mario?

**Comment by RISHI27-dot** [comment]
@gautam-dev-maker I apologise for the delay; I have updated the error logs.

**Comment by ChinmayLonkar** [comment]
@RISHI27-dot Can you please share the updates on the current status of solving the issue?
how much more time will it require to resolve the issue?

**Comment by RISHI27-dot** [comment]
@ChinmayLonkar with [this](https://github.com/SRA-VJTI/sra-board-component/pull/70) PR the firmware will be updated to the latest stable version of ESP-IDF.

**Comment by VedantParanjape** [comment]
@gautam-dev-maker @Jamm02 install script is not updated yet.

**Comment by SAtacker** [comment]
Can we close this now @gautam-dev-maker ?

**Comment by aPR0T0** [comment]
I am closing this issue as the major objective of porting to 4.4.3 is achieved
