### ISSUE TITLE
Add self_balancing+line_following code

### ISSUE THREAD

**Issue by gautam-dev-maker** [SRA-VJTI/Wall-E#109]
in WallE v2.1 we had an example code of bot following line while self balancing as well. So it would be good if for further wallE workshops we can add it here as well.

**Comment by Jamm02** [comment]
The current eklavya project is based on this task itself, which is aimed to be more efficient than the v2.1 firmware but we will have to wait till the conclusion of eklavya2022 for this, there's an option of adding the v2.1 right away.

**Comment by gautam-dev-maker** [comment]
Okay, but make sure the code is well formatted and follows the norms established in the codebase.

**Comment by aPR0T0** [comment]
Moving this discussion to a new issue for line and self balancing bot. 
comments over this issue are noted
