### ISSUE TITLE
No uniformity in internal Readme.md

### ISSUE THREAD

**Issue by gautam-dev-maker** [SRA-VJTI/Wall-E#111]
While [LSA Readme](https://github.com/SRA-VJTI/Wall-E/blob/master/2_LSA/README.md) contains `description of functions used`, [MPU Readme](https://github.com/SRA-VJTI/Wall-E/blob/master/3_MPU/README.md) doesn't contain any mention of functions used.

such non-uniformity in README.md should be resolved.

**Comment by ChinmayLonkar** [comment]
@Raghav323, you can proceed with adding the API description and flowchart for MPU. I expect this to be done before 7th November. If there's any problem you can post it here.

**Comment by Ayush-Kaura** [comment]
@Kshitijpatil16 Look at the readme for [switch_controlled_motor_parallel](https://github.com/SRA-VJTI/Wall-E/tree/master/5_switch_controlled_motor_parallel) and [switch_controlled_motor_normal](https://github.com/SRA-VJTI/Wall-E/tree/master/4_switch_controlled_motor_normal) proceed with adding the API description and flowchart, deadline 7th

@Omkar0820 Look at readme for [1_led_blink](https://github.com/SRA-VJTI/Wall-E/tree/master/1_led_blink) and [6_PWM](https://github.com/SRA-VJTI/Wall-E/tree/master/6_PWM) proceed with adding the API description and flowchart, deadline 7th
