### ISSUE TITLE
GitHub actions to verify install script

### ISSUE THREAD

**Issue by VedantParanjape** [SRA-VJTI/Wall-E#118]
Deploy a simple action that verifies install script across Ubuntu-(whichever we are going to use), Windows and mac osx.

GitHub has such runners available.

CC: @SAtacker @Jamm02 @gautam-dev-maker

**Comment by SAtacker** [comment]
Something like this should work https://github.com/WasmEdge/WasmEdge/blob/master/.github/workflows/test-install-script.yml
