### ISSUE TITLE
Fix the rendering issue

### ISSUE THREAD

**Issue by Shankari02** [SRA-VJTI/Wall-E#149]
The formula is not rendered properly [here](https://github.com/SRA-VJTI/Wall-E/blob/master/3_MPU/README.md#accelerometer-euler-angles) which requires to be fixed.

**Comment by AryanNanda17** [comment]
Can you please send ss of the formula? Assign me this.

**Comment by Shankari02** [comment]
@AryanNanda17 the formula is already committed but its not rendered properly. You can check out the code.
