### ISSUE TITLE
Windows ESP-IDF 4.2 Testing

### ISSUE THREAD

**Issue by SAtacker** [SRA-VJTI/Wall-E#67]
#### Setup
* ESP-IDF v4.2
* Installed using [esp-idf-tools-setup-2.4.exe](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/windows-setup.html)
* idf-python 3.8.7

#### Testing 
-------------------------------------------------------------

-  Wall-E_v2.2-beta\6_PWM  at origin/dev

| Status      | Task         | Output|
| ------------- |:-------------:| -----:|
|  <ul><li> [X]    </ul></li>    | Build | [Output](https://pastebin.com/cW5f43rJ) |
| <ul><li> [X]    </ul></li>        | Flash     |  [Output](https://pastebin.com/6gipYKHg) |
|  <ul><li> [X]    </ul></li>       | Monitor      |    [Output](https://pastebin.com/fRcnnrjM) |

#### Structure
```
C:\Users\shrey\Desktop\Wall-E_v2.2-beta>tree .
Folder PATH listing
Volume serial number is 005F0045 02C1:3324
C:\USERS\SHREY\DESKTOP\WALL-E_V2.2-BETA
├───1_led_blink
│   └───main
├───2_LSA
│   └───main
├───3_MPU
│   └───main
├───4_switch_controlled_motor_normal
│   └───main
├───5_switch_controlled_motor_parallel
│   └───main
├───6_PWM
│   └───main
├───7_line_following
│   ├───frontend
│   └───main
│       └───include
├───8_self_balancing
│   ├───frontend
│   └───main
│       └───include
├───components
│   └───sra-board-component
│       ├───.github
│       │   └───workflows
│       ├───assets
│       ├───docs
│       │   ├───def
│       │   ├───search
│       │   └───xml
│       ├───examples
│       │   ├───bar_graph
│       │   │   └───main
│       │   ├───lsa
│       │   │   └───main
│       │   ├───motor_driver_normal
│       │   │   └───main
│       │   ├───motor_driver_parallel
│       │   │   └───main
│       │   ├───mpu6050
│       │   │   └───main
│       │   ├───servos
│       │   │   └───main
│       │   └───switches
│       │       └───main
│       ├───include
│       └───src
└───windows_instructions
```

**Comment by VedantParanjape** [comment]
@SAtacker Please, create a script and tell 2-3 different friends to do the same that you did.

**Comment by VedantParanjape** [comment]
@SAtacker Should we shift to v4.4, what's your opinion on this ?

https://github.com/espressif/esp-idf/releases/tag/v4.4

**Comment by gautam-dev-maker** [comment]
A different issue #108 has been created regarding espidf upgradation. Hence this issue can now be closed.
